### PR TITLE
Call ./fuzzit with the correct arguments

### PR DESCRIPTION
**Pull request by jaqx0r**
Local regression needs `--local` and `--type regression`, not `--type=local-regression`.

### CODE REVIEW

**Comment by yevgenypats** [comment]
Actually this was updated in the last couple of version. this is `--type local-regression` now. this eliminate the need for additional flag

**Comment by jaqx0r** [comment]
Ok then I should update the version I fetch. This was why I had hoped you'd
just put the latest in the docker image.

**Comment by yevgenypats** [comment]
I think the problem regarding

**Comment by yevgenypats** [comment]
Sorry (pressed enter accidentally). I think the problem regarding latest version in general as well as putting the latest version in docker is that once there is a braking change in the latest version it will break your CI. maybe this is something that people want (this way they get notified of latest changes). you can download latest version of fuzzit CLI though  via `https://github.com/fuzzitdev/fuzzit/releases/latest/download/fuzzit_Linux_x86_64`

**Comment by jaqx0r** [comment]
Yep I realised that after I sent the message and have opted myself in to
that risk :) I hope you at least test the binary before it gets released
tho!

**Pull request closed without merging**
